name: Biography
favicon: null
layout_spectrum: 0.3509381818585098
typography_spectrum: 0.8405131695326418
title: Living my Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5521232376340777
  lightness: 0.9178107685875148
  saturation: 0.1298386873677373
  rhythmicContrast: 0.768081319052726
purpose: []
